export enum EventConstant {
    TOUCH_START = "touchstart",
    TOUCH_MOVE = "touchmove",
    POINTER_DOWN = "pointerdown",
    TOUCH_END = "touchend",
    POINTER_OVER = "pointerover",
    POINTER_OUT = "pointerout",
    POINTER_UP = "pointerup",
    MOUSE_UP = "mouseup",
    CLICK = "click"
}

export enum CustomEventConstant {
    SHOW_LOADING_SCREEN = "SHOW_LOADING_SCREEN",
    HIDE_LOADING_SCREEN = "HIDE_LOADING_SCREEN",
    CLEAR_BUTTON_PRESSED = "CLEAR_BUTTON_PRESSED",
    RESET_ON_PRESENTATION_COMPLETE = "RESET_ON_PRESENTATION_COMPLETE",
    DEAL_BUTTON_ENABLE_DISABLE = "DEAL_BUTTON_ENABLE_DISABLE",
    ENABLE_DISABLE_BUTTONS = "ENABLE_DISABLE_BUTTONS",
    COIN_ADDED = "COIN_ADDED",
    SHOW_CARDS = "SHOW_CARDS",
    NEXT_BET_COIN = "NEXT_BET_COIN",
    LAST_BET_COIN = "LAST_BET_COIN",
    UPDATE_METERS_ON_CARD_SHOWN = "UPDATE_METERS_ON_CARD_SHOWN"

}